---
title: "Covenant of Mayors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------


### Benchmaring de la implementacion de politicas sustentables

En este trabajo analizaremos que tan bien o mal es el desempeno de los intendentes del municipio (las acciones de los municipios de MAipu, ciudad, ...)

```{r}
C02 <- rnorm(50, 200, 30)
hist(C02)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Participacion de cada Municipio

```{r}
muni <- c("Capital","Chacras","Godoy","Maipu","Guayma","laera")
muniC02 <- c(300,350,270,320,412,330)
pie(muniC02, labels = muni,edges = 200, radius = 0.8)
```

### Transporte Publico

```{r}

```
RSU (Residuos Solidos Urbano) {data-width=350}
=========
```{r}

```
Reciclado {data-width=650}
=======
```{r}

```
RAE (Residuos de Aparatos Electricos){data-width=350}
========
```{r}

```
Benchmarking de intendentes
====
